theme: jekyll-theme-chirpy

lang: zh-CN
timezone: Asia/Shanghai

title: Tom
tagline: 个人博客
description: 记录技术和生活

url: "https://uestcheng.github.io"
baseurl: ""

github:
  username: uestcheng

twitter:
  username:

avatar:

social:
  name: Tom
  email:
  links:
    - https://github.com/uestcheng

google_site_verification:
bing_site_verification:

theme_mode:

paginate: 10

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true

sass:
  style: compressed


